use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::time::Instant;

use chrono::Utc;
use serde_json::{json, Value};

pub fn enabled() -> bool {
    std::env::var("BUILDERBOARD_TRACE_NATIVE_TOOLS").as_deref() == Ok("1")
}

pub fn trace_dir() -> PathBuf {
    std::env::var("BUILDERBOARD_TRACE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("runtime_traces"))
}

pub fn write_json(name: impl AsRef<str>, value: &Value) {
    if !enabled() {
        return;
    }
    if let Err(error) = write_json_inner(name.as_ref(), value) {
        eprintln!(
            "[native_tool_trace] failed to write {}: {}",
            name.as_ref(),
            error
        );
    }
}

pub fn append_jsonl(name: impl AsRef<str>, value: &Value) {
    if !enabled() {
        return;
    }
    if let Err(error) = append_jsonl_inner(name.as_ref(), value) {
        eprintln!(
            "[native_tool_trace] failed to append {}: {}",
            name.as_ref(),
            error
        );
    }
}

pub fn event(phase: &str, value: Value) {
    if !enabled() {
        return;
    }
    append_jsonl(
        "execution_timeline.jsonl",
        &json!({
            "timestamp": timestamp(),
            "phase": phase,
            "data": value,
        }),
    );
}

pub fn write_request(round: u32, body: &Value) {
    if !enabled() {
        return;
    }
    write_json(
        format!("request_round_{round:03}.json"),
        &redact_value(body),
    );
    ensure_protocol_comparison();
}

pub fn append_provider_event(round: u32, value: Value) {
    if !enabled() {
        return;
    }
    append_jsonl(
        format!("response_round_{round:03}.jsonl"),
        &json!({
            "timestamp": timestamp(),
            "event": redact_value(&value),
        }),
    );
}

pub fn write_conversation(round: u32, value: &Value) {
    if !enabled() {
        return;
    }
    write_json(format!("conversation_round_{round:03}.json"), value);
}

pub fn now() -> Instant {
    Instant::now()
}

pub fn elapsed_ms(started: Instant) -> u128 {
    started.elapsed().as_millis()
}

pub fn replay_request(path: impl AsRef<Path>) -> Result<Value, String> {
    let content = fs::read_to_string(path.as_ref()).map_err(|error| error.to_string())?;
    serde_json::from_str(&content).map_err(|error| error.to_string())
}

fn write_json_inner(name: &str, value: &Value) -> std::io::Result<()> {
    let dir = trace_dir();
    fs::create_dir_all(&dir)?;
    let path = dir.join(name);
    let pretty = serde_json::to_string_pretty(value)?;
    fs::write(path, format!("{pretty}\n"))
}

fn append_jsonl_inner(name: &str, value: &Value) -> std::io::Result<()> {
    let dir = trace_dir();
    fs::create_dir_all(&dir)?;
    let path = dir.join(name);
    let mut file = OpenOptions::new().create(true).append(true).open(path)?;
    let line = serde_json::to_string(value)?;
    writeln!(file, "{line}")
}

fn timestamp() -> String {
    Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Millis, true)
}

fn redact_value(value: &Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut redacted = serde_json::Map::new();
            for (key, value) in map {
                let lower = key.to_ascii_lowercase();
                if lower.contains("authorization")
                    || lower.contains("api_key")
                    || lower.contains("access_token")
                    || lower.contains("secret")
                    || lower.contains("token")
                {
                    redacted.insert(key.clone(), Value::String("[REDACTED]".to_string()));
                } else {
                    redacted.insert(key.clone(), redact_value(value));
                }
            }
            Value::Object(redacted)
        }
        Value::Array(items) => Value::Array(items.iter().map(redact_value).collect()),
        _ => value.clone(),
    }
}

fn ensure_protocol_comparison() {
    if !enabled() {
        return;
    }
    let dir = trace_dir();
    if fs::create_dir_all(&dir).is_err() {
        return;
    }
    let path = dir.join("OPENAI_PROTOCOL_COMPARISON.md");
    if path.exists() {
        return;
    }
    let content = r#"# OpenAI Protocol Comparison

Generated by `BUILDERBOARD_TRACE_NATIVE_TOOLS=1`.

## BuilderBoard Evidence

Inspect `request_round_*.json`, `response_round_*.jsonl`, `conversation_round_*.json`, and `execution_timeline.jsonl`.

## OpenCode Evidence

No working OpenCode wire capture was available in this repository at trace-generation time.

## Comparison Checklist

| Field | BuilderBoard evidence | OpenCode evidence | Classification |
| --- | --- | --- | --- |
| messages | See `request_round_*.json` | Not captured | Unknown |
| tools | See `request_round_*.json` | Not captured | Unknown |
| tool schemas | See `request_round_*.json` | Not captured | Unknown |
| tool_choice | See `request_round_*.json` | Not captured | Unknown |
| stream | See `request_round_*.json` | Not captured | Unknown |
| parallel_tool_calls | See `request_round_*.json` | Not captured | Unknown |
| assistant messages | See `conversation_round_*.json` | Not captured | Unknown |
| tool messages | See `conversation_round_*.json` | Not captured | Unknown |
| tool_call_id | See `response_round_*.jsonl` and `execution_timeline.jsonl` | Not captured | Unknown |
| finish_reason | See `response_round_*.jsonl` | Not captured | Unknown |
| response ordering | See `execution_timeline.jsonl` | Not captured | Unknown |

## Notes

This file intentionally does not infer OpenCode behavior without a raw request/response capture.
"#;
    let _ = fs::write(path, content);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn replay_request_reads_json() {
        let path = std::env::temp_dir().join("builderboard-replay-request.json");
        fs::write(&path, r#"{"model":"test","tools":[]}"#).unwrap();
        let replayed = replay_request(&path).unwrap();
        assert_eq!(replayed["model"], "test");
        let _ = fs::remove_file(path);
    }
}
